### ISSUE TITLE
require doc for in-app extensibility in s4 hana cloud

### ISSUE THREAD

**Issue by sanjayparabsap** [SAP/cloud-s4-sample-ext#3]
This is an issue for the [Custom Logic Samples](http://tiny.cc/s4-cust-logic) SAP S/4HANA Cloud Extensibility Scenario. Please fill the issue details using a template below.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can simply copy-paste them in your browser, they will be uploaded automatically. If it doesn't work, please provide external links to the images.

**Affected SAP S/4HANA version**
Place your SAP S/4HANA version here, e.g.: 1908.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by grenik** [comment]
Hi @sanjayparabsap, 

Please describe your issue in more details by editing the template above or removing parts which you feel unnecessary.

> require doc for in-app extensibility in s4 hana cloud

To learn how in-app extensibility works, please check some of the in-app samples. Follow the [link](https://extensibilityexplorer.cfapps.eu10.hana.ondemand.com/ExtensibilityExplorer/#/SearchList) and use the Tag ‘In-app’.

To know various in-app and side-by-side extensibility patterns and underlying documentation, explore the following [page](https://extensibilityexplorer.cfapps.eu10.hana.ondemand.com/ExtensibilityExplorer/#/ExtensibilityGuide).

In general, you also have learning Journey for Extensibility on SAP Help Portal: https://help.sap.com/doc/221f8f84afef43d29ad37ef2af0c4adf/HP_2.0/en-US/3ce3d27cccdc47e29af67ca45b9e66ad.html

If this doesn't answer your question, feel free to reopen the issue providing more details.

Best regards,
Nikolay
